name: Test Application

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-15
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: jdx/mise-action@v2
      
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.1.app
      
      - name: Fix plugins
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
      
      - run: tuist install
      
      # Build the project
      - name: Build the project
        run: tuist build Cork -- -derivedDataPath ./build
      # Find it 
      - name: Find .app bundles
        run: |
          find $HOME -type d -name '*.app'


      # Upload the build artifacts (e.g., .app or .ipa)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: '**/*.app'
